/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockLookupRouteImport } from './routes/stockLookup'
import { Route as LiveQuoteRouteImport } from './routes/liveQuote'
import { Route as IndexRouteImport } from './routes/index'

const StockLookupRoute = StockLookupRouteImport.update({
  id: '/stockLookup',
  path: '/stockLookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveQuoteRoute = LiveQuoteRouteImport.update({
  id: '/liveQuote',
  path: '/liveQuote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liveQuote': typeof LiveQuoteRoute
  '/stockLookup': typeof StockLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liveQuote': typeof LiveQuoteRoute
  '/stockLookup': typeof StockLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liveQuote': typeof LiveQuoteRoute
  '/stockLookup': typeof StockLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liveQuote' | '/stockLookup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liveQuote' | '/stockLookup'
  id: '__root__' | '/' | '/liveQuote' | '/stockLookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveQuoteRoute: typeof LiveQuoteRoute
  StockLookupRoute: typeof StockLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stockLookup': {
      id: '/stockLookup'
      path: '/stockLookup'
      fullPath: '/stockLookup'
      preLoaderRoute: typeof StockLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveQuote': {
      id: '/liveQuote'
      path: '/liveQuote'
      fullPath: '/liveQuote'
      preLoaderRoute: typeof LiveQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveQuoteRoute: LiveQuoteRoute,
  StockLookupRoute: StockLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
